### ISSUE TITLE
Synchronization raises `NoSuchWindowError` when window is closed

### ISSUE THREAD

**Issue by N0xFF** [makandra/capybara-lockstep#10]
Sample:

```ruby
window = window_opened_by do
  click_on "Open new window"
end

within_window(window) do
  find(".close_btn", text: "Close window").click
end
```

When we click the button that closes the window it raises the error:
```
Minitest::UnexpectedError: Selenium::WebDriver::Error::NoSuchWindowError: no such window: target window already closed
```

It happens when `synchronize_after` executes `Lockstep.auto_synchronize` in already closed window:

https://github.com/makandra/capybara-lockstep/blob/eb462be958798cc0a7377277a36a0d8ff02239d7/lib/capybara-lockstep/capybara_ext.rb#L22-L26

Stacktrace:
```
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.15.0/lib/selenium/webdriver/remote/response.rb:55:in `assert_ok'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.15.0/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.15.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.15.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.15.0/lib/selenium/webdriver/remote/http/default.rb:103:in `request'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.15.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.15.0/lib/selenium/webdriver/remote/bridge.rb:601:in `execute'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.15.0/lib/selenium/webdriver/remote/bridge.rb:126:in `alert_text'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.15.0/lib/selenium/webdriver/common/alert.rb:27:in `initialize'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.15.0/lib/selenium/webdriver/common/target_locator.rb:134:in `new'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/selenium-webdriver-4.15.0/lib/selenium/webdriver/common/target_locator.rb:134:in `alert'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/capybara-lockstep-2.0.0/lib/capybara-lockstep/page_access.rb:20:in `alert_present?'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/capybara-lockstep-2.0.0/lib/capybara-lockstep/client.rb:41:in `synchronize'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/capybara-lockstep-2.0.0/lib/capybara-lockstep/lockstep.rb:52:in `synchronize'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/capybara-lockstep-2.0.0/lib/capybara-lockstep/lockstep.rb:20:in `auto_synchronize'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/capybara-lockstep-2.0.0/lib/capybara-lockstep/capybara_ext.rb:25:in `block (2 levels) in synchronize_after'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/capybara-3.39.2/lib/capybara/node/element.rb:172:in `block in click'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/capybara-3.39.2/lib/capybara/node/element.rb:608:in `block in perform_click_action'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/capybara-3.39.2/lib/capybara/node/base.rb:84:in `synchronize'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/capybara-lockstep-2.0.0/lib/capybara-lockstep/capybara_ext.rb:244:in `synchronize'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/capybara-3.39.2/lib/capybara/node/element.rb:608:in `perform_click_action'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/capybara-3.39.2/lib/capybara/node/element.rb:171:in `click'
/home/virtual/Projects/Ruby/test/system/sample_test.rb:39:in `block (2 levels) in <class:SampleTest>'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/capybara-3.39.2/lib/capybara/session.rb:558:in `within_window'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/capybara-3.39.2/lib/capybara/dsl.rb:52:in `call'
/home/virtual/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/capybara-3.39.2/lib/capybara/dsl.rb:52:in `within_window'
/home/virtual/Projects/Ruby/test/system/sample_test.rb:31:in `block in <class:SampleTest>'
```

As workaround we [disable synchronization](https://github.com/makandra/capybara-lockstep/tree/master#disabling-synchronization) for some actions.

**Comment by triskweline** [comment]
Fixed in 2.0.1.
